on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
        - name: CHECKOUT
          uses: actions/checkout@v2
        - name: VERIFY COMMIT EXISTS IN origin/main
          run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
            git branch --remote --contains | grep origin/main
        - name: SET VERSION variable FROM TAG
          run: ech "VERSION=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_ENV
        - name: BUILD
          run: dotnet build -c Release /p:Version=${VERSION}
        - name: TEST
          run: dotnet test -c Release /p:Version=${VERSION} --no-build --output .
        - name: PUSH
          run: dotnet nuget push PolyBucket.Net.${VERSION}.nupkg --api-key ${GITHUB_TOKEN}
          env:
            GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
